# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vituix converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 480, 350))
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.listWidget.setDefaultDropAction(QtCore.Qt.LinkAction)
        self.listWidget.setObjectName("listWidget")
        self.pushButton_hats = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hats.setGeometry(QtCore.QRect(80, 420, 150, 80))
        self.pushButton_hats.setObjectName("pushButton_hats")
        self.pushButton_sams = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sams.setGeometry(QtCore.QRect(270, 420, 150, 80))
        self.pushButton_sams.setObjectName("pushButton_sams")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(50, 540, 400, 25))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_hats.setText(_translate("MainWindow", "Vituix HATS"))
        self.pushButton_sams.setText(_translate("MainWindow", "Vituix SAMS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
